language: generic
addons:
  apt:
    packages:
      - libc6:i386
      - libstdc++6:i386
env:
  global:
     - IDE_VERSION=1.8.5
before_install:
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
  - arduino --pref "boardsmanager.additional.urls=https://electroniccats.github.io/Arduino_Boards_Index/package_electroniccats_index.json" --install-boards electroniccts:samd > /dev/null
  - buildExampleSketch() { arduino --verbose-build --verify --board $1 $HOME/arduino-ide/examples/$2/$3/$3.ino; }
install:
  - mkdir -p $HOME/Arduino/hardware/electroniccats
  - ln -s $PWD $HOME/Arduino/hardware/electroniccats/samd
script:
  - buildExampleSketch electroniccats:samd:electroniccats_USB_Stick 01.Basics Blink
  - buildExampleSketch electroniccats:samd:electroniccats_meow_meow 01.Basics Blink
notifications:
  email:
    on_success: change
    on_failure: change
