name: Build

on: [pull_request, push]

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest
    
    steps:    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone Core Arduino SAMD
      shell: bash
      run: |
        git clone https://github.com/ElectronicCats/ArduinoCore-samd
    
    - name: '🚧 Build package'
      shell: bash
      run: |
        cd ArduinoCore-samd/extras
        ./pack.release_linux.bash
    
    - name: '📤 Upload artifact: package'
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: arduino-package
        path: release

      